### ISSUE TITLE
OAuth Google login not updating sidebar until page refresh

### ISSUE THREAD

**Issue by SamuelFerfort** [pedrolivaresanchez/emergency-cv#144]
Al iniciar sesión con Google OAuth después de haber cerrado una sesión previa, la sidebar sigue mostrando el botón de login hasta que se refresca la página manualmente. El login normal por email funciona correctamente.

Reproducción del bug:

https://github.com/user-attachments/assets/845de1cd-85bd-4620-87f2-144ec09a360e

**Comment by Pinx0** [comment]
Arreglado en https://github.com/pedrolivaresanchez/emergency-cv/pull/153
